'use client'

import { motion } from 'framer-motion'

export default function TermsOfServicePage() {
  return (
    <section className="relative min-h-screen pt-32 pb-20">
      <div className="absolute inset-0 pointer-events-none">
        <div
          className="absolute inset-0"
          style={{
            backgroundImage:
              'radial-gradient(ellipse 80% 50% at 50% 30%, hsl(var(--primary) / 0.06) 0%, transparent 70%)',
          }}
        />
      </div>

      <div className="relative max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <h1 className="text-4xl sm:text-5xl font-bold tracking-tight mb-4">
            Terms of Service
          </h1>
          <p className="text-sm text-muted-foreground mb-10">
            Last updated: February 20, 2026
          </p>

          <div className="space-y-8 text-muted-foreground leading-relaxed">
            <div>
              <h2 className="text-xl font-semibold text-foreground mb-3">1. Acceptance of Terms</h2>
              <p>
                By accessing or using TinyBaguette (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-foreground mb-3">2. Description of Service</h2>
              <p>
                TinyBaguette is an AI-powered project planning tool that helps you transform ideas into visual, actionable plans. The Service includes AI-generated content (plans, PRDs, prompts) powered by Google Gemini.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-foreground mb-3">3. User Accounts</h2>
              <ul className="list-disc pl-6 space-y-1.5">
                <li>You are responsible for maintaining the security of your account credentials.</li>
                <li>You must provide accurate information when creating an account.</li>
                <li>You are responsible for all activity that occurs under your account.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-foreground mb-3">4. Your Content</h2>
              <ul className="list-disc pl-6 space-y-1.5">
                <li>You retain ownership of all content you create using TinyBaguette, including plans, nodes, PRDs, prompts, and uploaded images.</li>
                <li>You grant us a limited license to store, process, and display your content solely to provide the Service.</li>
                <li>You are responsible for ensuring you have the right to upload any content, including images.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-foreground mb-3">5. AI-Generated Content</h2>
              <p>
                Content generated by our AI features (plans, PRDs, prompts, feature suggestions) is provided as-is. While we strive for accuracy, AI-generated content may contain errors or inaccuracies. You are responsible for reviewing and validating all AI-generated content before use.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-foreground mb-3">6. Acceptable Use</h2>
              <p className="mb-2">You agree not to:</p>
              <ul className="list-disc pl-6 space-y-1.5">
                <li>Use the Service for any unlawful purpose.</li>
                <li>Attempt to gain unauthorized access to the Service or its systems.</li>
                <li>Interfere with or disrupt the Service or its infrastructure.</li>
                <li>Use automated tools to scrape or abuse the Service.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-foreground mb-3">7. Service Availability</h2>
              <p>
                We strive to keep TinyBaguette available at all times but do not guarantee uninterrupted access. The Service may be temporarily unavailable for maintenance, updates, or due to circumstances beyond our control.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-foreground mb-3">8. Limitation of Liability</h2>
              <p>
                TinyBaguette is provided &ldquo;as is&rdquo; without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the Service.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-foreground mb-3">9. Changes to Terms</h2>
              <p>
                We may update these terms from time to time. Continued use of the Service after changes constitutes acceptance of the updated terms.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-foreground mb-3">10. Contact</h2>
              <p>
                Questions about these terms? Reach out at{' '}
                <a href="mailto:hello@tinybaguette.com" className="text-primary hover:underline">
                  hello@tinybaguette.com
                </a>.
              </p>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  )
}
